\section*{图形}
<<>>=
library(cluster)
library(xtable)
load("/media/lenovo/R/Rworkspace/Rstudio_space/multivariate/graph.RData")
envir.index <- graph[, c(1,2,4,6,10)]
df <- graph[ , c(2,4,6)]
row.names(df) <- graph[, 1]
agn1 <- agnes(df,  stand = TRUE)
glabel <- cutree(agn1, k=4)
@


<<>>=
first.vect <- envir.index[which(glabel == 1), 1]
first.vect[length(first.vect)+1:(9-length(first.vect)%%9)] <- rep(NA, 9-length(first.vect)%%9)
first.matrix <- matrix(first.vect,ceiling(length(first.vect)/9) , 9)

@
\Sexpr{print(xtable(first.matrix, caption="$SO_2$系统聚类——第一类"),
             include.colnames=FALSE, include.rownames=FALSE)}
          
<<>>=
first.vect <- envir.index[which(glabel == 2), 1]
first.vect[length(first.vect)+1:(9-length(first.vect)%%9)] <- rep(NA, 9-length(first.vect)%%9)
first.matrix <- matrix(first.vect,ceiling(length(first.vect)/9) , 9)

@
\Sexpr{print(xtable(first.matrix, caption="系统聚类——第二类"),
             include.colnames=FALSE, include.rownames=FALSE)}


<<>>=
first <- cbind(envir.index[which(glabel == 3 | glabel == 4), ],
             c(rep("第三类", 2), "第四类"))
names(first)[6] <- c("系统聚类类别")
@
\Sexpr{print(xtable(first, caption="系统聚类——第三类和第四类"), include.rownames=FALSE)}
          



